// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace XSSLG
{
    public partial class ClassData
    {
        /// <summary>ID</summary>
        [System.ComponentModel.DisplayName("ID")]
        public long Id { get; private set; }

        /// <summary>名字</summary>
        [System.ComponentModel.DisplayName("名字")]
        public string Name { get; private set; }

        /// <summary>描述</summary>
        [System.ComponentModel.DisplayName("描述")]
        public string Desc { get; private set; }

        /// <summary>职业的级别类型</summary>
        [System.ComponentModel.DisplayName("职业的级别类型")]
        public global::XSSLG.ClassDataClassLvType LvType { get; private set; }

        /// <summary>需要技巧等级</summary>
        [System.ComponentModel.DisplayName("需要技巧等级")]
        public List<global::XSSLG.TechniqueLevel> TechniqueLvArray { get; private set; }

        /// <summary>职业附加属性</summary>
        [System.ComponentModel.DisplayName("职业附加属性")]
        public long StatID { get; private set; }

        /// <summary>可以用魔法吗</summary>
        [System.ComponentModel.DisplayName("可以用魔法吗")]
        public bool CanMag { get; private set; }


        public static Int32 PID { get { return 0; } }
    }

    public partial class ClassDataArray
    {
        public List<long> Keys { get; private set; }

        public List<global::XSSLG.ClassData> Items { get; private set; }

        public string TableHash { get; private set; }


        public static Int32 PID { get { return 0;}}
    }

    public enum ClassDataClassLvType
    {
        /// <summary>基础</summary>
        [System.ComponentModel.Description("基础")]
        Unique = 0,
        Beginner = 1,
        /// <summary>中级</summary>
        [System.ComponentModel.Description("中级")]
        Intermediate = 2,
        /// <summary>高级</summary>
        [System.ComponentModel.Description("高级")]
        Advanced = 3,
        /// <summary>大师</summary>
        [System.ComponentModel.Description("大师")]
        Master = 4,
    }


}
