// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace XSSLG
{
    public partial class RoleData
    {
        /// <summary>角色ID</summary>
        [System.ComponentModel.DisplayName("角色ID")]
        public long Id { get; private set; }

        /// <summary>名字</summary>
        [System.ComponentModel.DisplayName("名字")]
        public string Name { get; private set; }

        /// <summary>描述</summary>
        [System.ComponentModel.DisplayName("描述")]
        public string Desc { get; private set; }

        /// <summary>基础数据</summary>
        [System.ComponentModel.DisplayName("基础数据")]
        public long StatID { get; private set; }

        /// <summary>初始等级</summary>
        [System.ComponentModel.DisplayName("初始等级")]
        public int Lv { get; private set; }

        /// <summary>当前初始职业</summary>
        [System.ComponentModel.DisplayName("当前初始职业")]
        public long ClassDataID { get; private set; }

        /// <summary>移动类型</summary>
        [System.ComponentModel.DisplayName("移动类型")]
        public global::XSSLG.RoleDataMovType MoveType { get; private set; }

        /// <summary>特技</summary>
        [System.ComponentModel.DisplayName("特技")]
        public List<long> AbilityIDArray { get; private set; }

        /// <summary>战技</summary>
        [System.ComponentModel.DisplayName("战技")]
        public List<long> CombatArtIDArray { get; private set; }

        /// <summary>魔法</summary>
        [System.ComponentModel.DisplayName("魔法")]
        public List<long> LearnMagicIDArray { get; private set; }

        /// <summary>技巧等级</summary>
        [System.ComponentModel.DisplayName("技巧等级")]
        public List<global::XSSLG.TechniqueLevel> TechniqueLvArray { get; private set; }

        /// <summary>纹章技能</summary>
        [System.ComponentModel.DisplayName("纹章技能")]
        public List<long> CrestIDArray { get; private set; }

        /// <summary>拥有的职业</summary>
        [System.ComponentModel.DisplayName("拥有的职业")]
        public List<long> ClassDataIDArray { get; private set; }

        /// <summary>学会的技能</summary>
        [System.ComponentModel.DisplayName("学会的技能")]
        public List<long> LearnSkillDataIDArray { get; private set; }

        /// <summary>行走图</summary>
        [System.ComponentModel.DisplayName("行走图")]
        public string Prefab { get; private set; }


        public static Int32 PID { get { return 0;}}

        //TODO 未实现
        private bool IsInit = false;
        public StatData Stat { get; private set; }
        public List<SkillData> CrestArray { get; private set; }
        public List<SkillData> AbilityArray { get; private set; }
        public ClassData ClassData { get; private set; }
        public List<ClassData> ClassDataArray { get; private set; }
        public List<SkillData> CombatArtArray { get; private set; }
        public List<SkillData> LearnMagicArray { get; private set; }
        public List<SkillData> LearnSkillDataArray { get; private set; }
    }

    public partial class RoleDataArray
    {
        public List<long> Keys { get; private set; }

        public List<global::XSSLG.RoleData> Items { get; private set; }

        public string TableHash { get; private set; }


        public static Int32 PID { get { return 0;}}
    }

    public enum RoleDataMovType
    {
        /// <summary>地面</summary>
        [System.ComponentModel.Description("地面")]
        Ground = 0,
        /// <summary>水面</summary>
        [System.ComponentModel.Description("水面")]
        Water = 1,
        /// <summary>飞行</summary>
        [System.ComponentModel.Description("飞行")]
        Fly = 2,
        /// <summary>骑马</summary>
        [System.ComponentModel.Description("骑马")]
        Ride = 3,
    }


}
